/**
 * PERSONAL PROFILE — edit this file to update your information.
 * Texts are bilingual { es, en }. Values wrapped in [BRACKETS] are placeholders:
 * the UI renders them as "pending" and never links to them.
 */
export const profile = {
  name: { first: 'Rafael', last: 'Pedraza' },
  fullName: 'Rafael Pedraza',
  initials: 'RP',
  domain: 'rafaelpedraza.dev',
  siteUrl: 'https://rafaelpedraza.dev',
  location: 'Valledupar, Cesar — Colombia',

  roles: [
    { es: 'Ingeniero de Software', en: 'Software Engineer' },
    { es: 'Arquitectura de Software', en: 'Software Architecture' },
    { es: 'Desarrollo asistido por IA', en: 'AI-Assisted Development' },
  ],
  degree: { es: 'Ingeniero de Sistemas · Especialista en Ingeniería de Software', en: 'Systems Engineer · Software Engineering Specialist' },

  tagline: { es: 'Construyo sistemas de software con código, arquitectura e IA.', en: 'Building software systems with code, architecture and AI.' },
  centralPhrase: { es: 'Construyendo software con código, arquitectura e IA.', en: 'Building software with code, architecture and AI.' },
  /** words highlighted in the central phrase */
  centralKeywords: ['código,', 'arquitectura', 'IA.', 'code,', 'architecture', 'AI.'],
  secondaryPhrase: { es: 'Ingeniería primero. La IA como herramienta.', en: 'Engineering first. AI as a tool.' },

  photo: {
    // Generated by `npm run images` from public/images/rafael-pedraza-v2.png (transparent cut-out)
    srcSet: '/images/rafael-pedraza-480.webp 480w, /images/rafael-pedraza-760.webp 760w',
    fallback: '/images/rafael-pedraza-760.jpg',
    face: '/images/rafael-pedraza-face.webp',
    alt: { es: 'Retrato de Rafael Pedraza, Ingeniero de Software', en: 'Portrait of Rafael Pedraza, Software Engineer' },
  },

  links: {
    // Email and phone are intentionally not published: messages arrive via the contact form → Telegram.
    linkedin: 'https://www.linkedin.com/in/rafael-pedraza/',
    github: '[ADD GITHUB URL]',
    cv: '/cv/Rafael-Pedraza-CV.pdf',
  },

  about: {
    // From the "Perfil profesional" section of the CV.
    summary: {
      es: 'Ingeniero de Sistemas con más de 10 años de experiencia en desarrollo de software y soporte especializado nivel III, enfocado en construir, mantener y evolucionar sistemas de información críticos para entidades públicas y privadas.',
      en: 'Systems Engineer with more than 10 years of experience in software development and level III specialized support, focused on building, maintaining and evolving critical information systems for public and private organizations.',
    },
    detail: {
      es: 'Experiencia en .NET, Angular, Oracle, SQL Server, integración de datos (ETL) y metodologías ágiles, en proyectos para MADR, CAR y DIGSA. Hoy incorporo la IA y la automatización como herramientas de trabajo.',
      en: 'Experience in .NET, Angular, Oracle, SQL Server, data integration (ETL) and agile methodologies, on projects for MADR, CAR and DIGSA. Today I use AI and automation as working tools.',
    },
  },

  /** `value: 'roles'` is computed from experience.ts */
  indicators: [
    { value: 10, suffix: '+', label: { es: 'Años de experiencia', en: 'Years of experience' } },
    { value: 'roles', suffix: '', label: { es: 'Cargos profesionales', en: 'Professional roles' } },
    { value: 5, suffix: '', label: { es: 'Motores de bases de datos', en: 'Database engines' } },
    { value: 3, suffix: '', label: { es: 'Entidades · MADR · CAR · DIGSA', en: 'Entities · MADR · CAR · DIGSA' } },
  ],

  capabilities: [
    { es: 'Ingeniería de software', en: 'Software engineering' },
    { es: 'Backend + Frontend', en: 'Backend + Frontend' },
    { es: 'Bases de datos', en: 'Databases' },
    { es: 'Integración de datos · ETL', en: 'Data integration · ETL' },
    { es: 'Cloud · DevOps', en: 'Cloud · DevOps' },
    { es: 'Desarrollo asistido por IA', en: 'AI-assisted development' },
  ],
} as const

export type Profile = typeof profile
